---
features:
  - |
    Adds :func:`qiskit.user_config.set_config` function which allows users to set
    the user config from Qiskit API. For Example::

      from qiskit.user_config import set_config
      set_config("circuit_drawer", "mpl", section="default", file="settings.conf")

    Optional arguments section and file has default values, 'default' and
    '~/.qiskit/settings.conf' respectively. To write the config to a specific file,
    add a file argument with the path to file and without one to write it to the
    default config file. Set the QISKIT_SETTINGS env variable to use the config
    files. Otherwise, the default config or the config in the 'default config
    file' will be used.
