# This code is part of Qiskit.
#
# (C) Copyright IBM 2017.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

version: 1.0.{build}

environment:
    matrix:
        - WHEEL: 1
          PYTHON: C:\Python35
          CIBW_BEFORE_BUILD: pip install -U Cython
          CIBW_SKIP: cp27-* cp34-*
          TWINE_USERNAME: qiskit
          CIBW_TEST_COMMAND: python {project}\examples\python\stochastic_swap.py
          TAG_SCENARIO: true

    # Set Travis CI variables for skipping the CI-unavailable tests.
    TRAVIS_PULL_REQUEST_SLUG: invalid
    TRAVIS_REPO_SLUG: invalid-but-different

for:
-
  # non-tagged scenario
  matrix:
    only:
      - TAG_SCENARIO: false

  skip_tags: true

-
  # tagged scenario
  matrix:
    only:
      - TAG_SCENARIO: true

  skip_non_tags: true


build: false
deploy: false
#      on:
#        APPVEYOR_REPO_TAG: true

skip_branch_with_pr: true

build_script:
  - if defined WHEEL (pip install cibuildwheel==0.10.1)
  - if defined WHEEL (pip install -U twine)
  - if defined WHEEL (cibuildwheel --output-dir wheelhouse)
  - if defined WHEEL (twine upload wheelhouse\*)
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
